Use Ubuntu 18.04 container instead if Ubuntu 18.04 runner
This should allow running this CI build even when GitHub removes support
for the runner.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,6 +23,7 @@ on:
 jobs:
   build:
     runs-on: ${{ matrix.runner || 'ubuntu-22.04' }}
+    container: ${{ matrix.container }}
     name: ${{ matrix.name }}
     strategy:
       fail-fast: false
@@ -39,8 +40,9 @@ jobs:
           - backend: valgrind
             name: Valgrind
           - backend: odbc
-            # There are many leak reports under Ubuntu 22.04, see #1008.
-            runner: ubuntu-18.04
+            # There are many leak reports under Ubuntu 22.04, see #1008, so
+            # run it in an older container.
+            container: ubuntu:18.04
             name: ODBC
           - backend: firebird
             name: Firebird
@@ -74,6 +76,24 @@ jobs:
       ASAN_OPTIONS: fast_unwind_on_malloc=0
 
     steps:
+      - name: Set up build system
+        run: |
+          case '${{ matrix.container }}' in
+            ubuntu:*)
+              export DEBIAN_FRONTEND=noninteractive
+
+              apt-get update -qq
+              apt-get install -qq coreutils g++ lsb-release sudo
+              ;;
+
+            '')
+              ;;
+
+            *)
+              echo '::error ::Unknown container kind.'
+              exit 1
+          esac
+
       - name: Checkout
         uses: actions/checkout@v3
 
